

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial (1380ee78-d935-4343-b661-cf37f3ab5c78)'
    appType: 'webApp'
    WebAppName: 
    VirtualApplication: 'Traffic Information System'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

- task: AppCenterTest@1
  inputs:
    artifactsDirectory: '$(Build.ArtifactStagingDirectory)/AppCenterTest'
    frameworkOption: 'appium'
    credentialsOption: 'serviceEndpoint'
    localeOption: 'en_US'