
variables:
  serviceConnectionToAzure: elizabethrozariosmrity.bis
   appName: TrafficInfo
 - task : CopyFiles@2
   displayName: CopyFiles
   inputs:
   SourceFolder: $(system.defaultworkingdirectory)
   Contents: '**'
    TargetFolder: $(build.artifactstagingdirectory)

 - task: PublishBuildArtifacts@1
   displayName: Publish Artifact
   inputs:
     PathPublish: $(build.artifactstagingdirectory)

- task: AzureWebApp@1
    displayName: Azure Web App Deploy
    inputs:
     azureSubscription: $(serviceConnectionTpAzure)
     appType: webAppLinux
     appName: $(TrafficInfo)
     package: $(build.artifactstagingdirectory)/**/*.war


 
 
